/**
 * ImageProvider — abstract interface for image generation.
 *
 * Wrapping all image calls behind this contract lets you swap out
 * the underlying provider (OpenAI / Stability / Replicate / …) without
 * touching any route or service code.
 */

export interface ImageGenerationRequest {
  /** Visual description for the image */
  prompt: string;
  /** Art style hint (e.g. "anime", "noir", "watercolor") */
  style: string;
  /** Desired size – provider implementations may translate this */
  size?: "1024x1024" | "1024x1792" | "1792x1024";
  /** Panel number within the comic (used for prompt enrichment) */
  panelNumber?: number;
  /**
   * Shared character / setting description that is prepended to EVERY
   * panel prompt so the image model sees consistent visual anchors.
   * Generated by the story-writing step.
   */
  characterSheet?: string;
  /**
   * Character reference image buffer. When provided, the image service
   * uses `images.edit` so gpt-image-1 can “see” the character design
   * and replicate it in every panel.
   */
  referenceImage?: Buffer;
}

export interface ImageGenerationResult {
  /** Public / temporary URL of the generated image (empty for base64-only models) */
  imageUrl: string;
  /** Raw image data as a Buffer — returned by gpt-image-1 (base64 models) */
  imageBuffer?: Buffer;
  /** Metadata about the generation – persisted alongside the panel */
  meta: ImageGenerationMeta;
}

export interface ImageGenerationMeta {
  /** Provider model identifier (e.g. "dall-e-3") */
  model: string;
  /** The final prompt that was sent to the provider */
  prompt: string;
  /** Requested art style */
  style: string;
  /** ISO-8601 timestamp of generation */
  createdAt: string;
  /** Estimated cost in USD (best-effort, can be 0) */
  costEstimate: number;
}

/**
 * Any image generation provider must implement this interface.
 */
export interface ImageProvider {
  readonly providerName: string;

  /**
   * Generate a single image from a text prompt.
   * Throws on failure so callers can handle retries / fallback.
   */
  generateImage(req: ImageGenerationRequest): Promise<ImageGenerationResult>;
}
